language: R
cache:
  packages: true
  directories:
  - $HOME/.npm
pandoc_version: 2.3.1

before_install:
  - nvm install stable
  - npm install netlify-cli -g
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${TRAVIS_COMMIT_MESSAGE:0:70}"

env:
  - NETLIFY_SITE_ID=ae487145-895c-4034-9090-bacf7bc99f9b
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'
# - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', quiet = TRUE)"
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book', quiet = TRUE)"

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      branch: master
